// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjwmuNxvbvciUtK6bvoPOWPTrpoP0r9q4',
    appId: '1:393113002269:web:09ab1721ec43f8c42781f4',
    messagingSenderId: '393113002269',
    projectId: 'plantpal-ff2b6',
    authDomain: 'plantpal-ff2b6.firebaseapp.com',
    storageBucket: 'plantpal-ff2b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Dx648KBR4rt1JZgIt_sPrsvuTwg04OE',
    appId: '1:393113002269:android:2af1b7b6f04f74be2781f4',
    messagingSenderId: '393113002269',
    projectId: 'plantpal-ff2b6',
    storageBucket: 'plantpal-ff2b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALTy7jJZDHYlFQ2_Lk7idF5otbEIQlTtg',
    appId: '1:393113002269:ios:6c8132230f4925392781f4',
    messagingSenderId: '393113002269',
    projectId: 'plantpal-ff2b6',
    storageBucket: 'plantpal-ff2b6.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALTy7jJZDHYlFQ2_Lk7idF5otbEIQlTtg',
    appId: '1:393113002269:ios:6c8132230f4925392781f4',
    messagingSenderId: '393113002269',
    projectId: 'plantpal-ff2b6',
    storageBucket: 'plantpal-ff2b6.firebasestorage.app',
    iosBundleId: 'com.example.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjwmuNxvbvciUtK6bvoPOWPTrpoP0r9q4',
    appId: '1:393113002269:web:b6fe9e0485b310762781f4',
    messagingSenderId: '393113002269',
    projectId: 'plantpal-ff2b6',
    authDomain: 'plantpal-ff2b6.firebaseapp.com',
    storageBucket: 'plantpal-ff2b6.firebasestorage.app',
  );
}
